### See https://github.com/Trick-17/clang-build

name = "fmath"

[fmath]
    [fmath.public-flags]
        compile = ["-Wno-unknown-pragmas", "-Wno-deprecated-declarations"]
    [fmath.windows.public-flags]
        compile = ["-DNOMINMAX"]
    [fmath.tests.flags]
        compile = ["-Wno-sign-compare"]


[fmath-omp] # TODO: openmp build
    [fmath-omp.public-flags]
        compile = ["-fopenmp", "-Wno-deprecated-declarations"]
        link    = ["-fopenmp"]
    [fmath-omp.windows.public-flags]
        compile = ["-DNOMINMAX"]
    [fmath-omp.tests.flags]
        compile = ["-Wno-sign-compare"]